version: '4.x'

services:

  api:  
    build:
        context: .
        dockerfile: apps/api/Dockerfile
    container_name: baobbab-api
    command: pnpm --filter './apps/api' dev
    volumes:
      - ./apps/api:/apps/api
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ponpon
      DB_NAME: baobbab_db
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.5-alpine
    container_name: baobbab-postgres
    ports:
      - 5435:5432
    expose:
      - "5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ponpon
      POSTGRES_DB: baobbab_db
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data
      - ./services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

