FROM node:18-alpine

WORKDIR /app

# Installer PNPM
RUN npm install -g pnpm @nestjs/cli

# Copier le monorepo config
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig*.json ./

# Installer toutes les dépendances globales
RUN pnpm install --frozen-lockfile

# Copier le code complet
COPY apps/api ./apps/api
COPY packages ./packages

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["pnpm", "start"]
