name: Lint

on:
  push:
    branches:
      -dev
  pull_request:
    branches:
      -staging
      -main

jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.7.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm lint