name: "Typecheck"

on:
  push:
    branches: ['dev']     
  pull_request:
    types: [opened, reopened]
    branches: [ 'staging', 'main']
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.7.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run Typecheck type check
        run: pnpm tsc --noEmit